name: CI

on:
  push:
    branches:
      - main  # Executa o workflow ao fazer push na branch principal
  pull_request:
    branches:
      - main  # Executa o workflow em pull requests para a branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Ajuste a versão de acordo com o seu projeto

      - name: Install dependencies
        run: npm install
        working-directory: ./cypress-heroes

      - name: Start development server
        run: npm run dev &
      
      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3000
        env:
          CI: true
          
      - name: Run Cypress Tests
        run: DEBUG=cypress:* npx cypress run

      - name: Upload Cypress Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Cypress Result
          path: |
            cypress/screenshots
            cypress/videos
            cypress/results
          if-no-files-found: ignore
